kind: Mesh
apiVersion: servicemesh.oci.oracle.com/v1beta1
metadata:
  name: oci-sm-app
  namespace: oci-sm-app
spec:
  compartmentId: ocid1.compartment.oc1..aaaaaaaanjtbllhqxcg67dq7em3vto2mvsbc6pbgk4pw6cx37afzk3tngmoa
  certificateAuthorities:
    - id: ocid1.certificateauthority.oc1.phx.amaaaaaassl65iqa36wfx2wvwjuvsy23acpx3o6qzqm5vkrbg4haqw5bjucq
  mtls:
    minimum: PERMISSIVE