@endpoint-local = http://localhost:8080

@endpoint-cluster = https://sm.shukawam.com

GET {{endpoint-local}}/catalog HTTP/1.1

###
GET {{endpoint-local}}/catalog/2 HTTP/1.1

###
GET {{endpoint-local}}/greet HTTP/1.1