kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        version: v2
    spec:
      containers:
        - name: catalog
          image: ${DOCKER_SERVER}/${REPOSITORY}:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
          - name: api
            containerPort: 8080
          env:
            - name: app.imageUrl
              value: "true"
      imagePullSecrets:
        - name: oci-sm-app-secret
