kind: Service
apiVersion: v1
metadata:
  name: catalog
  labels:
    app: catalog
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        version: v1
    spec:
      containers:
      - name: catalog
        image: ${DOCKER_SERVER}/${REPOSITORY}:${TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 8080
        env:
          - name: app.imageUrl
            value: "false"
      imagePullSecrets:
        - name: oci-sm-app-secret
---
