kind: Service
apiVersion: v1
metadata:
  name: client
  labels:
    app: client
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        version: v1
    spec:
      containers:
        - name: client
          image: ${DOCKER_SERVER}/${REPOSITORY}:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8080
      imagePullSecrets:
        - name: oci-sm-app-secret
---

